import { Difficulty, Exam, ExamStatus, Skill, TestType } from '../../types/client';
import { createGenericSlice } from './main/genericSlice';

const exams: Exam[] = [
	{
		id: 'e1',
		createdBy: 'u1',
		status: ExamStatus.Approved,
		title: 'Luyện tập IELTS Reading',
		description: 'Bài thi thực hành phần Đọc hiểu IELTS',
		duration: 60,
		difficulty: Difficulty.Intermediate,
		skill: Skill.Reading,
		testType: TestType.IELTS,
		tagIds: ['t1', 't2'],
	},
	{
		id: 'e2',
		createdBy: 'u2',
		status: ExamStatus.Approved,
		title: 'Bài thi TOEIC Listening',
		description: 'Nghe và chọn câu trả lời đúng',
		duration: 45,
		difficulty: Difficulty.Beginner,
		skill: Skill.Listening,
		testType: TestType.TOEIC,
		tagIds: ['t2'],
	},
	{
		id: 'e3',
		createdBy: 'u1',
		status: ExamStatus.Pending,
		title: 'IELTS Writing Task 1',
		description: 'Luyện tập Task 1 phần Viết IELTS',
		duration: 40,
		difficulty: Difficulty.Intermediate,
		skill: Skill.Writing,
		testType: TestType.IELTS,
		tagIds: ['t1'],
	},
	{
		id: 'e4',
		createdBy: 'u2',
		status: ExamStatus.Rejected,
		title: 'Đọc hiểu TOEIC',
		description: 'Luyện tập đọc hiểu cho TOEIC',
		duration: 50,
		difficulty: Difficulty.Advanced,
		skill: Skill.Reading,
		testType: TestType.TOEIC,
		tagIds: ['t2'],
	},
	{
		id: 'e5',
		createdBy: 'u1',
		status: ExamStatus.Rejected,
		title: 'Thi thử IELTS Speaking',
		description: 'Luyện tập Speaking với các đề mẫu',
		duration: 20,
		difficulty: Difficulty.Intermediate,
		skill: Skill.Speaking,
		testType: TestType.IELTS,
		tagIds: ['t1'],
	},
	{
		id: 'e6',
		createdBy: 'u2',
		status: ExamStatus.Pending,
		title: 'TOEIC Listening Nâng cao',
		description: 'Bài thi nghe nâng cao cho TOEIC',
		duration: 60,
		difficulty: Difficulty.Advanced,
		skill: Skill.Listening,
		testType: TestType.TOEIC,
		tagIds: ['t2'],
	},
	// Exam mock mới để dễ test làm bài
	{
		id: 'e7',
		createdBy: 'u1',
		status: ExamStatus.Approved,
		title: 'IELTS Reading – Đề thi thử số 1',
		description: 'Đề thi thử cho phần Đọc hiểu IELTS với hai đoạn văn và nhiều dạng câu hỏi khác nhau.',
		duration: 30,
		difficulty: Difficulty.Beginner,
		skill: Skill.Reading,
		testType: TestType.IELTS,
		tagIds: ['t1'],
	},
];

const examsSlice = createGenericSlice<Exam>('exams', exams);

export const {
	addItem: addExam,
	updateItem: updateExam,
	removeItem: removeExam,
	setList: setExams,
} = examsSlice.actions;
export default examsSlice.reducer;
